### ISSUE TITLE
Filter to select what is detected / downloadable

### ISSUE THREAD

**Issue by slitzer** [manyfold3d/manyfold#1377] opened 2023-07-26 21:29 UTC
Is there a way to specify what file types are displayed in the viewer?

The problem im trying to solve is some folders have a few files and thats fine - when there are over 20 or so files in a collection this becomes a pain to manaully download each file.  I know there is a request to add a d/l button, however I imagine this will be problematic when dealing with large  files (and trying to zip them all would take a while, most likely timeout

Instead could we can a fiilter to choose what gets detected, and able to be downloaded (similar to LYS files) this way I could add a .zip or .7z file to this and have the option to download the zip file (which would be all files in 1 download)

Cheers

**Comment by Floppy** [comment] 2023-07-27 09:07
Nice idea! The list of file types is somewhat hardcoded at the moment, but could be made customisable.

**Comment by Floppy** [comment] 2024-02-08 12:31
Going to consider this a duplicate of #764, I think. Trying to collect the ideas for that all in one place.

**Closed by Floppy** 2024-02-08 12:31 UTC
Labels: duplicate, feature
