### ISSUE TITLE
Upload files to existing model

### ISSUE THREAD

**Issue by aneurinprice** [manyfold3d/manyfold#2453] opened 2024-07-27 16:54 UTC
**Describe the solution you'd like**
The ability to upload files after a models creation

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Floppy** [comment] 2024-07-28 09:01
I heartily agree! Duplicate of #1091 though, so I'll close this one. Coming soon I hope!

**Closed by Floppy** 2024-07-28 09:01 UTC
Labels: feature
