### ISSUE TITLE
Documention Files (pdf, mkv etc)

### ISSUE THREAD

**Issue by lloydpick** [manyfold3d/manyfold#1736] opened 2024-01-13 17:38 UTC
I have quite a few models that include pdf assembly instructions or BOM lists and the same goes for assembly videos. I've stored these along side the 3d models, however it appears manyfold has no way of showing these back to the user. I'm not looking for an embedded player or viewer, but perhaps extra links on the right navigation to simply download them?

**Comment by Floppy** [comment] 2024-01-14 14:11
Agreed, I should add those to the indexer so they show up.

**Comment by Floppy** [comment] 2024-01-14 14:12
I mean, really, it should index *every* file in the folder.

**Comment by Floppy** [comment] 2024-02-08 12:26
Duplicate of #764

**Closed** 2024-02-08 12:30 UTC
Labels: duplicate, feature
