### ISSUE TITLE
Upload Preview from model page

### ISSUE THREAD

**Issue by SilverbackConnor** [manyfold3d/manyfold#2699] opened 2024-09-17 21:12 UTC
**Is your feature request related to a problem? Please describe.**
As is, when uploading a model, often times there's not a suitable object to make a preview out of (ae, presupported chitbox archives, etc) - being able to add a preview image after the fact via the model's edit page would help a lot in regards to usability. I don't think there's a way to do this atm?

**Describe the solution you'd like**
A "Add Preview" Button/prompt/field under the preview file dropdown would be nice, but the exact location doesn't really matter.

**Comment by Floppy** [comment] 2024-09-18 08:01
As it happens, I wrote this a couple of days ago - just doing a bit of debugging before it releases soon!

Closing as duplicate of #1091

**Closed by Floppy** 2024-09-18 08:01 UTC
Labels: feature
