### ISSUE TITLE
Self-inflicted pathing problems might not be easy to see issues

### ISSUE THREAD

**Issue by ksuquix** [manyfold3d/manyfold#1109] opened 2023-03-14 23:43 UTC
If you end up with a combination of names/whatnot that a rename tries to move the current model to a subdirectory of itself, it randomly fails without a good error.  Perhaps returning the text error of the failed "rename" system call would be good.

**Comment by ksuquix** [comment] 2023-03-14 23:44
permissions problems etc probably fall into this same category.

**Comment by Floppy** [comment] 2023-06-12 06:03
This should be improved by #1254, but moving a model to a subdir of itself will still probably explode unhelpfully.

**Comment by Floppy** [comment] 2024-09-13 14:02
This needs testing under the new Shrine file backend

**Comment by Floppy** [comment] 2024-09-20 14:14
Confirmed under new backend, if you really try you can move things into themselves, and it completely loses the files Fun!

**Comment by Floppy** [comment] 2024-09-20 14:29
No, turns out I'm a fool looking in the wrong place. Moving to a subdir of self fails (as it should), and #2727 fixes the error messages that appear afterwards.

**Closed** 2024-09-20 14:35 UTC
Labels: bug, funded
