### ISSUE TITLE
Which files to upload

### ISSUE THREAD

**Issue by ikljaic-nubilum** [manyfold3d/manyfold#1896] opened 2024-02-23 11:41 UTC
I have tried toi upload STL files, but All I see a zip and gzp to be allowed. In which format is it supossed to be inside? Does it have to be in root? Does it have to be in a folder substructure?

**Comment by ikljaic-nubilum** [comment] 2024-02-23 11:44
When I try to upload a zip file, all I get is an erro message "We're sorry, but something went wrong."

Are there anywhere some instructions on how to use it?

**Comment by Floppy** [comment] 2024-02-23 13:17
Hm, zip files containing STL files should work ok - can you attach the file you tried here?

Currently you can't upload indivdual STL files - there's an open feature request for it in #1737.

**Comment by Floppy** [comment] 2024-06-26 09:13
I suspect that the zip/gzip problem was caused by #1584, which is now fixed.

**Comment by Floppy** [comment] 2024-06-28 11:08
#1737 covers the "upload single file as model" thing, so I'll close this issue because those others should solve the problems you had here. Feel free to reopen if there's something still not right after v0.70.0 comes out.

**Closed by Floppy** 2024-06-28 11:08 UTC
Labels: bug
