### ISSUE TITLE
Cannot remove duplicate files

### ISSUE THREAD

**Issue by kiguy2052** [manyfold3d/manyfold#2301] opened 2024-06-24 00:44 UTC
**Describe the bug**

**To Reproduce**
Upload the same model twice
Remove one of the models from the folder mounted outside docker
back in manyfold, scan and make sure the model is tagged 
try to purge/delete the empty duplicate tagged model

**Expected behavior**
The model should be deleted

**Screenshots**
![image](https://github.com/manyfold3d/manyfold/assets/10635940/1bc1368d-6fde-402d-8c0b-277fb050618c)

docker logs:
db-1     | 2024-06-23 21:12:53.332 UTC [287] ERROR:  update or delete on table "model_files" violates foreign key constraint "fk_rails_b5ac05b6e3" on table "model_files"
db-1     | 2024-06-23 21:12:53.332 UTC [287] DETAIL:  Key (id)=(1367) is still referenced from table "model_files".
db-1     | 2024-06-23 21:12:53.332 UTC [287] STATEMENT:  DELETE FROM "model_files" WHERE "model_files"."id" = $1

**Desktop (please complete the following information):**
 - OS: debian 11 proxmox LXC, client is windows 10
 - Browser FireFox
 - Version 127

**Comment by Floppy** [comment] 2024-07-01 11:09
This feels very similar to https://github.com/manyfold3d/manyfold/issues/1929, in that it's a failure in removing relationships that the database is enforcing. Probably has a very similar solution.

**Comment by Floppy** [comment] 2024-07-01 11:10
Actually, given that it's complaining about a link from `model_files` to `model_files`, it well might be the *same* error; do you know if the model had linked supported and unsupported files @kiguy2052?

**Comment by kiguy2052** [comment] 2024-07-01 20:23
I didn't notice that at the time, but going back through, the models I had
issues with all had linked supported and unsupported models.

**Comment by Floppy** [comment] 2024-07-01 20:58
Ok cool, pretty sure this is the same issue then. Thanks :)

**Comment by Floppy** [comment] 2024-07-01 21:25
closing as duplicate of #1929

**Closed by Floppy** 2024-07-01 21:25 UTC
Labels: bug, duplicate
