### ISSUE TITLE
OIDC login fails due to redirect URI always being localhost

### ISSUE THREAD

**Issue by Natureshadow** [manyfold3d/manyfold#2990] opened 2024-10-19 14:12 UTC
**Describe the bug**

When using OIDC login. Manyfold always uses `localhost` in the redirect URI.

**To Reproduce**

Configure OIDC:

```plain
      OIDC_CLIENT_ID: xxxxx
      OIDC_CLIENT_SECRET: yyyyy
      OIDC_ISSUER: https://ticdesk.teckids.org
      OIDC_NAME: Teckids-Account
      FORCE_OIDC: enabled
      MULTIUSER: enabled
      PUBLIC_HOSTNAME: manyfold.teckids.org
      HTTPS_ONLY: enabled
```

Try to log in.

The redirect URI passed to the OIDC provider begins with `http://localhost/`.

**Expected behavior**

The real public URL of Manyfold is used as `redirect_uri` when connecting to the OIDC provider.

**Comment by Floppy** [comment] 2024-10-19 14:39
That's odd, because setting PUBLIC_HOSTNAME should be what you need there. Try setting PUBLIC_PORT as well, it might be that it's checking for both (which would indeed be a bug)

**Comment by Natureshadow** [comment] 2024-10-21 19:30
Setting `PUBLIC_PORT` as well gets me further. I am now at `Could not authenticate you from OpenIDConnect because "Unknown".`

**Comment by Natureshadow** [comment] 2024-10-21 19:31
Ah, that's due to an Internal Server Error in our IdM.

So, indeed, setting `PUBLIC_PORT` as well seems to solve this issue.

**Comment by Floppy** [comment] 2024-10-21 21:25
Interesting! If that's a standard port, that certainly shouldn't be necessary for it to use the hostname. I'll investigate!

**Comment by Floppy** [comment] 2024-11-07 14:16
Duplicate of #3021 , which is fixed and will be in a patch release soon.

**Closed by Floppy** 2024-11-07 14:16 UTC
Labels: bug
